# site settings
title: Tales from the Foundry
subtitle: justinbaur
email: justinbaur@outlook.com
description: Thoughts and adventures from corporate development
baseurl: "/tales"
url:
author: Justin Baur
street_address:
city:
state: Wisconsin
zip_code:
country: United States
phone:

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 2

# social settings
500px_url:
facebook_url:
github_url: https://github.com/justinbaur
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
